package io.stringx;

import android.app.Activity;
import android.content.ComponentCallbacks;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.res.Configuration;
import android.content.res.Resources;
import android.os.Build;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import java.util.List;
import java.util.Locale;

/**
 * <a href="https://www.stringx.io">stringX</a> SDK for automatic app translations
 * stringX library mimics translated resources with native translations by forcing locale
 * and letting user choose to use them as app translation or fallback to default app language
 * Translations are generated by the
 * <a href="https://play.google.com/store/apps/details?id=io.stringx">stringX App</a>
 * available in Google Play.
 */
public class StringX implements StringXLanguageReceiver.OnLanguageChanged, ComponentCallbacks {
    private static final String PREFERENCE_NAME = "StringX";
    private static final String KEY_LANGUAGE_ENABLED = "KEY_ENABLED_";
    private static final String KEY_OPT_OUT = "KEY_OPTED_OUT";
    private final Options options;
    private SharedPreferences preferences;
    private Locale defaultLocale;
    @Nullable
    private Locale locale;
    private TranslationListener listener;
    private boolean isForcingDefaultLocale;

    private StringX(Options options) {
        Context context = options.getContext();
        this.options = options;
        this.defaultLocale = Locale.getDefault();
        this.preferences = context.getSharedPreferences(PREFERENCE_NAME, Context.MODE_PRIVATE);
        StringXLanguageReceiver.from(context).addListener(this);
        context.registerComponentCallbacks(this);
        try {
            forceDefault();
        } catch (UnsupportedLanguageException e) {
            SXLog.e("Unsupported locale" + defaultLocale.getDisplayLanguage() + "-" + defaultLocale.getDisplayCountry(), e);
            if (listener != null) {
                listener.onLanguageNotSupported(defaultLocale);
            }
        }
    }

    /**
     * Constructs single entry point for stringX SDK
     *
     * @param options configuration of the library, see {@link Options}
     */
    public static StringX init(Options options) {
        return new StringX(options);
    }

    /**
     * Call this method to receive stringX instance
     *
     * @return {@link StringX} instance
     * @throws IllegalStateException if stringX is not initialised.
     *                               See <a href="https://www.stringx.io/docs/guides">integration guide</a>
     */
    public static StringX get(@NonNull Context context) {
        if (isInitialised(context)) {
            return ((Translatable) context.getApplicationContext()).getStringX();
        } else {
            throw new IllegalStateException("StringX is not initialised. Follow instructions here https://www.stringx.io/docs/guides");
        }
    }

    private static boolean isInitialised(Context context) {
        Context applicationContext = context.getApplicationContext();
        return applicationContext instanceof Translatable &&
                ((Translatable) applicationContext).getStringX() != null;
    }

    /**
     * Forces {@link Locale} on the given context
     *
     * @param context can be Application Context or Activity, depending on what scope changes should take
     * @param locale  {@link Locale} to force
     */
    public void forceLocale(Context context, @Nullable Locale locale) {
        forceLocale(context, locale, false);
    }

    /**
     * Verifies if translation hint can be shown to the user.
     * This is when device language is supported,
     * translation is not yet enabled
     * and user didn't opted out from automatic translations
     *
     * @return true if
     */
    public boolean isTranslationHintAvailable() {
        try {
            return isTranslationAvailable() &&
                    !isEnabled() &&
                    !isOptOut();
        } catch (UnsupportedLanguageException e) {
            SXLog.w("Unsupported device language!");
            return false;
        }
    }

    /**
     * {@link Options} of the library
     *
     * @return options under which library is configured
     */
    public Options getOptions() {
        return options;
    }

    /**
     * Restarts the application to apply the changes made on application context
     */
    public void restart() {
        options.getRestartStrategy().restart();
    }

    boolean isTranslationAvailable() {
        try {
            return getOptions().getAutoTranslatedLanguages().contains(getDeviceLanguage());
        } catch (UnsupportedLanguageException e) {
            return false;
        }
    }

    void forceDefault() throws UnsupportedLanguageException {
        boolean translationAvailable = isTranslationAvailable();
        boolean enabled = isEnabled();
        if (translationAvailable && !enabled) {
            forceLocale(options.getContext(), getAppDefaultLanguage().toLocale(), true);
        }
    }

    TranslationListener getListener() {
        return listener;
    }

    /**
     * Registers for translation events, See {@link TranslationListener}
     *
     * @param listener
     */
    public void setListener(TranslationListener listener) {
        this.listener = listener;
    }

    private void forceLocale(Context context, @Nullable Locale locale, boolean isDefault) {
        if (locale == null) {
            return;
        }
        SXLog.d("Forcing " + locale.getDisplayLanguage());
        isForcingDefaultLocale = isDefault;
        this.locale = locale;
        Resources res = context.getResources();
        Configuration configuration = res.getConfiguration();
        Locale.setDefault(locale);
        if (Build.VERSION.SDK_INT >= 17) {
            configuration.setLocale(locale);
        } else {
            configuration = new Configuration(res.getConfiguration());
            configuration.locale = locale;
        }
        res.updateConfiguration(configuration, res.getDisplayMetrics());
    }

    boolean isForcingLocale() {
        return !isForcingDefaultLocale && locale != null && !locale.equals(defaultLocale);
    }

    boolean isEnabled() throws UnsupportedLanguageException {
        return preferences.getBoolean(getPreferenceKey(), false);
    }

    /**
     * Enables translation for current {@link Locale}
     *
     * @param isEnabled
     */
    public void setEnabled(boolean isEnabled) {
        try {
            preferences
                    .edit()
                    .putBoolean(getPreferenceKey(), isEnabled)
                    .apply();
        } catch (UnsupportedLanguageException e) {
            SXLog.w("Couldn't toggle translation. Language is not supported!");
        }
    }

    private boolean isOptOut() {
        return preferences.getBoolean(KEY_OPT_OUT, false);
    }

    /**
     * Turns off stringX translations
     *
     * @param isOptOut
     */
    public void setOptOut(boolean isOptOut) {
        preferences
                .edit()
                .putBoolean(KEY_OPT_OUT, isOptOut)
                .apply();
    }

    private String getPreferenceKey() throws UnsupportedLanguageException {
        return KEY_LANGUAGE_ENABLED + getDeviceLanguage().getCode();
    }

    /**
     * Shows translation hint to the user to pick, disable or dismiss automatic translation
     *
     * @param activity
     * @return true if hint has been presented to user, false otherwise
     */
    public boolean showTranslationHint(Activity activity) {
        if (!isTranslationHintAvailable()) {
            return false;
        }
        Intent intent = new Intent(activity, StringXOverlayActivity.class);
        activity.startActivityForResult(intent, StringXOverlayActivity.REQUEST_CODE);
        return true;
    }

    List<Language> getSupportedLanguages() {
        return options.getSupportedLanguages();
    }

    @Override
    public void onLanguageChanged(Language language) {
        defaultLocale = language.toLocale();
    }

    Language getDeviceLanguage() throws UnsupportedLanguageException {
        return Language.fromLocale(defaultLocale);
    }

    Language getAppDefaultLanguage() {
        return getOptions().getDefaultLanguage();
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        try {
            forceDefault();
        } catch (UnsupportedLanguageException ignored) {
        }
    }

    @Override
    public void onLowMemory() {

    }

    /**
     * Notifies about translation events. Useful eg. for analytics
     */
    public interface TranslationListener {

        /**
         * Notifies that the user closed the pop-up to turn on translation
         */
        void onTranslationCanceled();

        /**
         * Notifies that the user opted out from automatic translation for his locale
         */
        void onTranslationDisabled();

        /**
         * Notifies that the user switched to automatic translations
         */
        void onTranslationEnabled();

        /**
         * Notifies that current {@link Locale} is not supported
         */
        void onLanguageNotSupported(Locale defaultLocale);
    }
}
