package mobi.klimaszewski.linguist;

import android.app.Activity;
import android.content.ComponentCallbacks;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.res.Configuration;
import android.content.res.Resources;
import android.os.Build;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import java.util.List;
import java.util.Locale;

/**
 * <a href="https://linguist.klimaszewski.mobi/">Linguist</a> SDK for automatic app translations
 * Linguist library mimics translated resources with native translations by forcing locale
 * and letting user choose to use them as app translation or fallback to default app language
 * Translations are generated by the
 * <a href="https://play.google.com/store/apps/details?id=mobi.klimaszewski.linguist.services">Linguist App</a>
 * available in Google Play.
 */
public class Linguist implements LinguistLanguageReceiver.OnLanguageChanged, ComponentCallbacks {
    private static final String PREFERENCE_NAME = "Linguist";
    private static final String KEY_LANGUAGE_ENABLED = "KEY_ENABLED_";
    private static final String KEY_OPT_OUT = "KEY_OPTED_OUT";
    private final Options options;
    private final Locale originalLocale;
    private SharedPreferences preferences;
    private TranslationListener listener;
    private Locale forcedLocale;

    private Linguist(Options options) {
        Context context = options.getContext();
        this.options = options;
        this.preferences = context.getSharedPreferences(PREFERENCE_NAME, Context.MODE_PRIVATE);
        LinguistLanguageReceiver.from(context).addListener(this);
        context.registerComponentCallbacks(this);
        originalLocale = Locale.getDefault();
    }

    /**
     * Constructs single entry point for Linguist SDK
     *
     * @param options configuration of the library, see {@link Options}
     */
    public static Linguist init(Options options) {
        return new Linguist(options);
    }

    /**
     * Call this method to receive Linguist instance
     *
     * @return {@link Linguist} instance
     * @throws IllegalStateException if Linguist is not initialised.
     *                               See <a href="https://www.stringx.io/docs/guides">integration guide</a>
     */
    public static Linguist get(@NonNull Context context) {
        if (isInitialised(context)) {
            return ((Translatable) context.getApplicationContext()).getLinguist();
        } else {
            throw new IllegalStateException("Linguist is not initialised. Follow instructions here https://www.stringx.io/docs/guides");
        }
    }

    private static boolean isInitialised(Context context) {
        Context applicationContext = context.getApplicationContext();
        return applicationContext instanceof Translatable &&
                ((Translatable) applicationContext).getLinguist() != null;
    }

    public static Context wrap(Context context) {
        Linguist linguist = Linguist.get(context);
        if (linguist.isForcingLocale()) {
            return linguist.forceLocale(context, linguist.forcedLocale);
        }
        try {
            Language currentLanguage = linguist.getCurrentLanguage();
            if (linguist.getOptions().getSupportedLanguages().contains(currentLanguage) || linguist.isEnabled()) {
                return context;
            } else {
                return linguist.forceLocale(context, linguist.getAppDefaultLanguage().toLocale());
            }
        } catch (UnsupportedLanguageException e) {
            return context;
        }
    }

    /**
     * Verifies if translation hint can be shown to the user.
     * This is when device language is supported,
     * translation is not yet enabled
     * and user didn't opted out from automatic translations
     *
     * @return true if
     */
    private boolean isTranslationHintAvailable() {
        try {
            return !isForcingLocale() &&
                    isTranslationAvailable() &&
                    !isEnabled() &&
                    !isOptOut();
        } catch (UnsupportedLanguageException e) {
            LinguistLog.w("Unsupported device language!");
            return false;
        }
    }

    public boolean isForcingLocale() {
        return forcedLocale != null;
    }

    /**
     * {@link Options} of the library
     *
     * @return options under which library is configured
     */
    public Options getOptions() {
        return options;
    }

    /**
     * Restarts the application to apply the changes made on application context
     */
    public void restart() {
        options.getRestartStrategy().restart();
    }

    boolean isTranslationAvailable() {
        try {
            Language originalLanguage = Language.fromLocale(originalLocale);
            List<Language> autoTranslatedLanguages = getOptions().getAutoTranslatedLanguages();
            return autoTranslatedLanguages.contains(originalLanguage);
        } catch (UnsupportedLanguageException e) {
            return false;
        }
    }

    Context forceAppDefault(Context context) {
        return forceLocale(context, getAppDefaultLanguage().toLocale());
    }

    TranslationListener getListener() {
        return listener;
    }

    /**
     * Registers for translation events, See {@link TranslationListener}
     *
     * @param listener
     */
    public void setListener(TranslationListener listener) {
        this.listener = listener;
    }

    /**
     * Forces {@link Locale} on the given context
     *
     * @param context can be Application Context or Activity, depending on what scope changes should take
     * @param locale  {@link Locale} to force
     */
    Context forceLocale(Context context, @Nullable Locale locale) {
        if (locale == null) {
            return context;
        }
        LinguistLog.d("Forcing " + locale.getDisplayLanguage());
        Resources res = context.getResources();
        Locale.setDefault(locale);
        Configuration config = new Configuration(res.getConfiguration());
        if (Build.VERSION.SDK_INT >= 17) {
            config.setLocale(locale);
            context = context.createConfigurationContext(config);
        } else {
            config.locale = locale;
            res.updateConfiguration(config, res.getDisplayMetrics());
        }

        return context;
    }

    boolean isEnabled() throws UnsupportedLanguageException {
        return preferences.getBoolean(getPreferenceKey(), false);
    }

    /**
     * Enables translation for current {@link Locale}
     *
     * @param isEnabled
     */
    public void setEnabled(boolean isEnabled) {
        try {
            preferences
                    .edit()
                    .putBoolean(getPreferenceKey(), isEnabled)
                    .apply();
        } catch (UnsupportedLanguageException e) {
            LinguistLog.w("Couldn't toggle translation. Language is not supported!");
        }
    }

    private boolean isOptOut() {
        return preferences.getBoolean(KEY_OPT_OUT, false);
    }

    /**
     * Turns off Linguist translations
     *
     * @param isOptOut
     */
    public void setOptOut(boolean isOptOut) {
        preferences
                .edit()
                .putBoolean(KEY_OPT_OUT, isOptOut)
                .apply();
    }

    private String getPreferenceKey() throws UnsupportedLanguageException {
        return KEY_LANGUAGE_ENABLED + Language.fromLocale(originalLocale).getCode();
    }

    /**
     * Shows translation hint to the user to pick, disable or dismiss automatic translation
     *
     * @param activity
     * @return true if hint has been presented to user, false otherwise
     */
    public boolean showTranslationHint(Activity activity) {
        if (!isTranslationHintAvailable()) {
            return false;
        }
        Intent intent = new Intent(activity, LinguistOverlayActivity.class);
        activity.startActivityForResult(intent, LinguistOverlayActivity.REQUEST_CODE);
        return true;
    }

    List<Language> getSupportedLanguages() {
        return options.getSupportedLanguages();
    }

    @Override
    public void onLanguageChanged(Language language) {
    }

    Language getCurrentLanguage() throws UnsupportedLanguageException {
        return Language.fromLocale(Locale.getDefault());
    }

    Language getAppDefaultLanguage() {
        return getOptions().getDefaultLanguage();
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
    }

    @Override
    public void onLowMemory() {

    }

    public void setForcedLocale(Locale forcedLocale) {
        this.forcedLocale = forcedLocale;
    }

    /**
     * Notifies about translation events. Useful eg. for analytics
     */
    public interface TranslationListener {

        /**
         * Notifies that the user closed the pop-up to turn on translation
         */
        void onTranslationCanceled();

        /**
         * Notifies that the user opted out from automatic translation for his locale
         */
        void onTranslationDisabled();

        /**
         * Notifies that the user switched to automatic translations
         */
        void onTranslationEnabled();

        /**
         * Notifies that current {@link Locale} is not supported
         */
        void onLanguageNotSupported(Locale defaultLocale);
    }
}
