package mobi.klimaszewski.linguist;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.Handler;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static android.content.Intent.FLAG_ACTIVITY_CLEAR_TASK;
import static android.content.Intent.FLAG_ACTIVITY_NEW_TASK;

/**
 * Configuration of {@link Linguist} library
 */
public class Options {
    private final Context context;
    private final Language defaultLanguage;
    private List<Class> stringClasses;
    private List<Class> excludedClasses;
    private List<Integer> excludedStringIds;
    private List<Language> supportedLanguages;
    private List<Language> autoTranslatedLanguages;
    private RestartStrategy restartStrategy;

    private Options(Context context, Language defaultLanguage) {
        this.context = context;
        this.defaultLanguage = defaultLanguage;
    }

    public List<Class> getStringClasses() {
        return stringClasses;
    }

    private void setStringClasses(List<Class> stringClasses) {
        this.stringClasses = stringClasses;
    }

    public List<Class> getExcludedClasses() {
        return excludedClasses;
    }

    private void setExcludedClasses(List<Class> excludedClasses) {
        this.excludedClasses = excludedClasses;
    }

    public Language getDefaultLanguage() {
        return defaultLanguage;
    }

    public List<Language> getSupportedLanguages() {
        return supportedLanguages;
    }

    private void setSupportedLanguages(List<Language> supportedLanguages) {
        this.supportedLanguages = supportedLanguages;
    }

    public List<Integer> getExcludedStringIds() {
        return excludedStringIds;
    }

    private void setExcludedStringIds(List<Integer> excludedStringIds) {
        this.excludedStringIds = excludedStringIds;
    }

    public RestartStrategy getRestartStrategy() {
        return restartStrategy;
    }

    private void setRestartStrategy(RestartStrategy restartStrategy) {
        this.restartStrategy = restartStrategy;
    }

    public Context getContext() {
        return context;
    }

    public List<Language> getAutoTranslatedLanguages() {
        return autoTranslatedLanguages;
    }

    private void setAutoTranslatedLanguages(List<Language> autoTranslatedLanguages) {
        this.autoTranslatedLanguages = autoTranslatedLanguages;
    }

    public interface RestartStrategy {
        void restart();
    }

    /**
     * Builds {@link Options}
     *
     * @see <a href="https://www.stringx.io/docs/guides">Guides</a> for example setup
     */
    public static class Builder {
        private final Context context;
        private final Language defaultLanguage;
        private final List<Class> supportedStrings;
        private final List<Class> excludedStrings;
        private Translatable translatable;
        private Language[] supportedLanguages;
        private Language[] autoTranslatedLanguages;
        private int[] excludedStringIds;
        private RestartStrategy restartStrategy;

        /**
         * Constructs {@link Builder}
         *
         * @param context
         * @param defaultLanguage application default language (the same as language used in values resource folder)
         */
        public Builder(Context context, Language defaultLanguage) {
            this.context = context;
            this.defaultLanguage = defaultLanguage;
            supportedStrings = new ArrayList<>();
            excludedStrings = new ArrayList<>();
        }

        /**
         * Provides languages that application supports natively.
         * Eg. Application with resources values and values-pl should declare
         * {@link Language#English} and {@link Language#Polish} as supported languages
         *
         * @param supportedLanguages
         */
        public Builder setSupportedLanguages(Language... supportedLanguages) {
            this.supportedLanguages = supportedLanguages;
            return this;
        }

        /**
         * Provides languages, which are generated by <a href="https://play.google.com/store/apps/details?id=io.stringx">Linguist app</a>.
         *
         * @param autoTranslatedLanguages
         */
        public Builder setAutoTranslatedLanguages(Language... autoTranslatedLanguages) {
            this.autoTranslatedLanguages = autoTranslatedLanguages;
            return this;
        }

        /**
         * Adds string classes as a source for resources.
         * eg. If your applciationId/packageName is com.my.super.app,
         * then the required resources class will be com.my.super.app.R.string.class
         *
         * @param clazz string resources class
         */
        public Builder addStrings(Class clazz) {
            supportedStrings.add(clazz);
            return this;
        }

        /**
         * Excludes from translation all strings within given string class eg.
         * <p>.excludeStrings(com.google.android.gms.R.string.class)
         * .excludeStrings(android.support.design.R.string.class)
         * .excludeStrings(android.support.v7.appcompat.R.string.class)
         *
         * @param clazz excluded string classes
         */
        public Builder excludeStrings(Class clazz) {
            excludedStrings.add(clazz);
            return this;
        }

        /**
         * Linguist needs to restart the application, when new Language is set.
         * You can change default behavior by injecting your restarting strategy
         *
         * @param restartStrategy strategy of app restart after configuration change
         */
        public Builder setRestartStrategy(RestartStrategy restartStrategy) {
            this.restartStrategy = restartStrategy;
            return this;
        }

        /**
         * Linguist excludes resources be comparing default language with one of supported languages,
         * however if there is only default language supported, then you should exclude strings that
         * should not be automatically translated, like client id's or urls
         * <p>
         * <p>
         * eg.
         * R.string.default_web_client_id, R.string.firebase_database_url,
         * R.string.gcm_defaultSenderId, R.string.google_api_key, R.string.google_app_id,
         * R.string.google_crash_reporting_api_key, R.string.google_storage_bucket, R.string.project_id
         *
         * @param stringId excluded string resources
         */
        public Builder excludeString(int... stringId) {
            excludedStringIds = stringId;
            return this;
        }

        /**
         * Builds {@link Options}
         */
        public Options build() {
            Options options = new Options(context, defaultLanguage);
            if (excludedStringIds == null) {
                excludedStringIds = new int[0];
            }
            ArrayList<Integer> ids = new ArrayList<>();
            for (int stringId : excludedStringIds) {
                ids.add(stringId);
            }

            options.setExcludedStringIds(ids);
            options.setStringClasses(supportedStrings);
            if (supportedLanguages == null) {
                supportedLanguages = new Language[]{defaultLanguage};
            }
            excludedStrings.add(mobi.klimaszewski.linguist.R.string.class);
            options.setExcludedClasses(excludedStrings);
            ArrayList<Language> languages = new ArrayList<>();
            boolean isDefaultLanguageAdded = false;
            for (Language supportedLanguage : supportedLanguages) {
                if (supportedLanguage == defaultLanguage) {
                    isDefaultLanguageAdded = true;
                }
                languages.add(supportedLanguage);
            }
            if (!isDefaultLanguageAdded) {
                languages.add(defaultLanguage);
            }
            options.setSupportedLanguages(languages);
            List<Language> autoTranslatedLanguages;
            if (this.autoTranslatedLanguages == null) {
                autoTranslatedLanguages = Collections.emptyList();
            } else {
                autoTranslatedLanguages = new ArrayList<>(Arrays.asList(this.autoTranslatedLanguages));
                autoTranslatedLanguages.removeAll(languages);
            }
            options.setAutoTranslatedLanguages(autoTranslatedLanguages);
            if (restartStrategy == null) {
                restartStrategy = new DefaultRestartStrategy(context);
            }
            options.setRestartStrategy(restartStrategy);

            return options;
        }
    }

    private static class DefaultRestartStrategy implements RestartStrategy {

        private final Context context;

        public DefaultRestartStrategy(Context context) {
            this.context = context;
        }

        @Override
        public void restart() {
            new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    triggerRebirth(context);
                }
            }, 100);
        }

        public static void triggerRebirth(Context context) {
            PackageManager packageManager = context.getPackageManager();
            Intent intent = packageManager.getLaunchIntentForPackage(context.getPackageName());
            intent.addFlags(FLAG_ACTIVITY_NEW_TASK | FLAG_ACTIVITY_CLEAR_TASK); // In case we are called with non-Activity context.
            context.startActivity(intent);
            if (context instanceof Activity) {
                ((Activity) context).finish();
            }
            Runtime.getRuntime().exit(0);
        }
    }
}
